FROM centos:latest

RUN yum install epel-release -y

RUN yum install shellinabox openssh-server openssh-clients -y

RUN sshd-keygen

RUN  /usr/sbin/sshd -f /etc/ssh/sshd_config ; echo "/usr/sbin/sshd -f /etc/ssh/sshd_config " >> /root/.bashrc	

RUN echo "redhat" | passwd root --stdin

RUN useradd pyuser -s /bin/python

RUN echo "redhat" | passwd pyuser --stdin


RUN sed -i 's/OPTS=/#OPTS=/g' /etc/sysconfig/shellinaboxd ;    echo 'OPTS="-t -s /:SSH:0.0.0.0"' >> /etc/sysconfig/shellinaboxd

RUN echo "shellinaboxd -t -s /:pyuser:pyuser:/home/pyuser:/bin/python -p 4200" >> /root/.bashrc





