- import_playbook: prerequisites.yml
- hosts: localhost
  tasks:
   - include_vars: var.yml
   - name: "Building Dockerfile"
     docker_image:
       dockerfile: Dockerfile_paas_web_shellinabox
       path: "{{ loc }}"
       name: paas_web_shellinabox:v1
   - name: "Launching paas_shellinabox"
     docker_container:
       detach: yes
       interactive: yes
       tty: yes
       name: paas
       image: paas_web_shellinabox:v1
       published_ports:
        - "{{ free_port }}:4200"
       
        
